const songList = [
  {
    id: "007",
    name: "Wellerman",
    artist: "Nathan Evans",
    url: "/public/music/Wellerman.mp3",
    cover: "/public/images/Wellerman.jpg",
    category: "Nhac tre",
    type: "US-UK",
  },
  {
    id: "001",
    name: "Đi theo bóng mặt trời",
    artist: "Đen Vâu",
    url: "/public/music/ditheobongmattroi.mp3",
    cover: "/public/images/ditheobongmattroi.jpg",
    category: "Nhac tre",
    type: "V-pop",
  },
  {
    id: "002",
    name: "Lộn xộn 2",
    artist: "Đen Vâu",
    url: "/public/music/lonxon.mp3",
    cover: "/public/images/lonxon.jpg",
    category: "Nhac tre",
    type: "V-pop",
  },
  {
    id: "003",
    name: "Đi về nhà",
    artist: "Đen Vâu",
    url: "/public/music/divenha.mp3",
    cover: "/public/images/divenha.jpg",
    category: "Nhac tre",
    type: "V-pop",
  },
  {
    id: "004",
    name: "Lâu đài tình ái cover",
    artist: "Trần Thiện Thanh",
    url: "/public/music/laudaitinhai.mp3",
    cover: "/public/images/laudaitinhai.png",
    category: "Nhac tre",
    type: "V-pop",
  },
  {
    id: "005",
    name: "Tiếng trống Branung",
    artist: "Phạm Thu Hà & Drum Hùng Cường",
    url: "/public/music/tiengtrongbranung.mp3",
    cover: "/public/images/tiengtrongbranung.jpg",
    category: "Nhac tre",
    type: "V-pop",
  },
  {
    id: "006",
    name: "Khuê mộc lan (Kuimu Wolf)",
    artist: "Huong Ly & Jombie",
    url: "/public/music/khuemoclan.mp3",
    cover:
      "https://photo-resize-zmp3.zadn.vn/w480_r1x1_webp/cover/d/2/6/1/d26117831a67fecf48f95c99823cecc6.jpg",
    category: "Nhac tre",
    type: "V-pop",
  },
  {
    id: "008",
    name: "Renai-Circulation",
    artist: "Kana Hanazawa",
    url: "/public/music/Renai-Circulation.mp3",
    cover: "/public/images/Renai-Circulation.jpg",
    category: "Nhac tre",
    type: "J-pop",
  },
  {
    id: "009",
    name: "Blue Bird",
    artist: "Ikimono Gakari",
    url: "/public/music/blue-bird.mp3",
    cover: "/public/images/bluebird.jpg",
    category: "Nhac tre",
    type: "J-pop",
  },
  {
    id: "010",
    name: "Your name",
    artist: "Radwimps",
    url: "/public/music/your-name.mp3",
    cover: "/public/images/your-name.jpg",
    category: "Nhac tre",
    type: "J-pop",
  },
  {
    id: "011",
    name: "Amadare No Uta",
    artist: "Inori Minase & Yurika Kubo",
    url: "/public/music/Amadare-No-Uta.mp3",
    cover: "/public/images/grillasttour.jpg",
    category: "Nhac tre",
    type: "J-pop",
  },
  {
    id: "012",
    name: "Summertime",
    artist: "K391",
    url: "/public/music/Summertime.mp3",
    cover:
      "https://photo-resize-zmp3.zadn.vn/w480_r1x1_webp/cover/8/2/9/9/82998293f8c34d7999339490d0b90118.jpg",
    category: "Nhac dien tu",
    type: "EDM",
  },
  {
    id: "013",
    name: "Paradise",
    artist: "Alan Walker, K-391, Boy In Space",
    url: "/public/music/BoyinSpace.mp3",
    cover:
      "https://photo-resize-zmp3.zadn.vn/w480_r1x1_webp/cover/a/c/0/f/ac0fbb661d98b18a88985cbbd538dd97.jpg",
    category: "Nhac dien tu",
    type: "EDM",
  },
  {
    id: "014",
    name: "OhMyWay",
    artist: "Alan Walker, Sabrina Carpenter, Farruko",
    url: "/public/music/OhMyWay.mp3",
    cover:
      "https://photo-resize-zmp3.zadn.vn/w480_r1x1_webp/cover/d/f/a/d/dfadd8acafaec178f08bc68e8a2e9387.jpg",
    category: "Nhac dien tu",
    type: "EDM",
  },
  {
    id: "015",
    name: "Vùng lá me bay",
    artist: "Như Quỳnh",
    url: "/public/music/VungLaMeBay.mp3",
    cover:
      "https://photo-resize-zmp3.zadn.vn/w480_r1x1_webp/cover/d/8/4/d/d84dd1b4eacc2015054e7124bc83340d.jpg",
    category: "Nhac tru tinh",
    type: "tru-tinh",
  },
  {
    id: "016",
    name: "Bậu ơi đừng khóc",
    artist: "Phi Nhung",
    url: "/public/music/BauOiDungKhoc.mp3",
    cover:
      "https://photo-resize-zmp3.zadn.vn/w480_r1x1_webp/cover/2/5/8/3/2583ac830626d322279cc30bbb387673.jpg",
    category: "Nhac tru tinh",
    type: "tru-tinh",
  },
  {
    id: "017",
    name: "Nỗi nhớ mưa phai",
    artist: "Mạnh Quỳnh",
    url: "/public/music/NoiNhoMuaPhai.mp3",
    cover:
      "https://photo-resize-zmp3.zadn.vn/w480_r1x1_webp/cover/a/9/6/0/a96097ccfc26b5c3985adb5c8a31be8c.jpg",
    category: "Nhac tru tinh",
    type: "tru-tinh",
  },
];
export default songList;
